extends: site.yaml

mode: production
media_url: /users/rano/media
base_url: /users/rano
deploy_root: deploy_production

publisher:
    ssh:
        type: hyde.ext.publishers.ssh.SSH
        username: rano
        server: put.url.here
        target: /
