extends: site.yaml

mode: production
media_url: /~vergari/media
base_url: /~vergari/
deploy_root: deploy-prod

publisher:
    pyfs:
        type: hyde.ext.publishers.pyfs.PyFS
        username: vergari
        url: ftp://193.204.187.10:22
        target: /
